#!/bin/sh

cd $1
npm run build

if [ "`uname`" == "Darwin" ]; then
  sed -i .bak 's/\/static/static/g' ./build/index.html
else
  sed -i 's/\/static/static/g' ./build/index.html
fi

rm -f ./build/index.html.bak
