#!/bin/sh

if [ -z "$REACT_APP_BUILD" ]; then
  echo "You must specify env REACT_APP_BUILD"
  exit 1
fi

mkdir -p $REACT_APP_BUILD
cd $REACT_APP_BUILD
cd ..

npm install
npm run build

if [ "`uname`" == "Darwin" ]; then
  sed -i .bak 's/\/static/static/g' ./build/index.html
else
  sed -i 's/\/static/static/g' ./build/index.html
fi

rm -f ./build/index.html.bak
