#!/bin/sh

if [ -z "$REACT_APP_BUILD" ]; then
  echo "You must specify env REACT_APP_BUILD"
  exit 1
fi

mkdir -p $REACT_APP_BUILD
cd $REACT_APP_BUILD
cd ..

npm install
PUBLIC_URL=%PUBLIC_URL% npm run build
